name: Release
on:
  push:
    branches: [main]
  workflow_dispatch:  # This line enables manual triggering
permissions:
  contents: write
  deployments: write
jobs:
  activate:
    runs-on: ubuntu-latest
    if: |
      github.repository == 'hossein-lap/asciidoctor-docs-ui' && !startsWith(github.event.head_commit.message, 'Release ')
    steps:
    - run: echo ok go
  build:
    needs: activate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Tag and release
      env:
        GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx gulp release
